apiVersion: v1
kind: Pod
metadata:
  labels:
    run: apache1
  name: application
spec:
  containers:
  - image: paketobuildpacks/httpd:0.7
    name: apache1
    ports:
      - containerPort: 80
    imagePullSecrets:
    - name: ochirdorj
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
