apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 4
  selector: # This is a label selector(I should be careful this one)
    app: nginx
  template: #Pod template
    metadata:
      name: nginx #Pod name
      labels:
        release: stable #this stable is the label of pod and it should be same as Replication selector
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80