apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: release
        operator: in
        values:
          - stable
          - in-progress
          - deployed
  template:
    metadata:
      labels:
        release: stable
    spec:
      containers:
      - name: nginx
        image: nginx