apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: new-pod
  name: new-pod
spec:
  volumes:
    - name: new-pod-volume
      persistentVolumeClaim:
        claimName: app-volume-claim
  containers:
  - image: nginx
    name: new-pod
    resources: {}
    volumeMounts:
      - mountPath: "/data"
        name: new-pod-volume
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}