apiVersion: v1                # Kubernetes API version used in this YAML decriptor
kind: Pod                     # Type of Kubernetes object/resource
metadata:                     # Pod metadata (name, labels, annotations and so on)
  name: nginx-pod             # Pod Name
  labels: 
    app: nginx                # Key value pair Label value has charactory limit
    env: development
  annotations:
    app: This application pod is running nginx  application # There is no annotation selection and query
    
spec:                         # Pod Specification/Contents (list of containers, volumes, image, ports and so on)
  containers:
  - image: nginx              # Container Image
    name: nginx-container     # Container Name
    ports:            
    - containerPort: 80       # The Port the container is listening on
      protocol: TCP
---

apiVersion: v1                # Kubernetes API version used in this YAML decriptor
kind: Pod                     # Type of Kubernetes object/resource
metadata:                     # Pod metadata (name, labels, annotations and so on)
  name: apache-pod             # Pod Name
  labels:
    app: apache
    env: development
  annotations:
    app: This application pod is running nginx  application # There is no annotation selection and query
spec:                         # Pod Specification/Contents (list of containers, volumes, image, ports and so on)
  containers:
  - image: nginx              # Container Image
    name: apache-container     # Container Name
    ports:            
    - containerPort: 80       # The Port the container is listening on
      protocol: TCP
      # Required fields are: apiVersion, Kind, Metadata, Spec
      # Required field - a kms 