apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod1
  name: httpd
  namespace: application
spec:
  containers:
  - image: paketobuildpacks/httpd:0.7.37
    name: pake 
    ports:
     - containerPort: 80
       protocol: TCP
