apiVersion: v1
kind: Service
metadata:
  name: simple-lb
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80 #Loadbalancer port
      targetPort: 80 #Container port
  type: LoadBalancer