apiVersion: v1
kind: Pod
metadata:
  labels:
    app: web
  name: apache-pod
spec:
  containers:
  - image: httpd
    name: apache-container
    ports:
    - containerPort: 80
      protocol: TCP
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: web
  name: nginx-pod
spec:
  containers:
  - image: nginx
    name: nginx-container
    ports:
    - containerPort: 80
      protocol: TCP
  restartPolicy: Always