apiVersion: v1
kind: Service
metadata:
  name: simple-service
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80 #Service port number
      targetPort: 80 #Container port number

      #THis is default service
